FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  coconut.py /home/myapp/
COPY  coconut.png /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/coconut.py
FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  coconut.py /home/myapp/
COPY  coconut.png /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/coconut.py
